2025SinhanHackaton/GongGuYoung

.gitignore

feat : 깃 이그노어 초기 설정

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/controller/AuthController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/controller/MemberController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/request/LoginRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/request/SignupRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/response/MemberSummary.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/response/SignupResponse.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/entity/Member.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/repository/MemberRepository.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/service/MemberService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/global/utils/GlobalExceptionHandler.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/global/utils/PasswordUtil.java

login, logout, signup

---

frontend/src/components/auth/register-form.tsx
frontend/src/lib/auth-context.tsx
frontend/src/pages/Page.tsx
frontend/src/pages/auth/login/Page.tsx
frontend/src/pages/auth/register/Page.tsx
frontend/vite.config.ts

Feat: 회원가입, 로그인, 로그아웃 개발(로컬서버)

---

frontend/src/components/auth/login-form.tsx
frontend/src/components/auth/register-form.tsx
frontend/src/lib/auth-context.tsx
frontend/src/pages/Page.tsx

Feat: 로그인 라우터 수정 및 로그인 버그 해결 및 메인페이지 좀 꾸밈

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/grouppurchase/controller/GroupPurchaseController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/grouppurchase/controller/GroupPurchaseControllerImpl.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/grouppurchase/dto/response/GroupPurchaseResponse.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/grouppurchase/entity/GroupPurchase.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/grouppurchase/service/GroupPurchaseService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/grouppurchase/service/GroupPurchaseServiceImpl.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/global/exception/GlobalExceptionHandler.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/global/exception/GroupPurchaseNotFoundException.java

- 공동 구매 단건 api 추가
- 공동 구매 단건 조회의 옵션에 따른 조회수 증가 로직 추가
- Controller Swagger 설정
- 공동 구매 전역 핸들러 추가

Feature: 공동 구매 단건 조회 및 조회수 증가 로직 구현

---

frontend/src/pages/create-campaign/Page.tsx

Feat: 상품 선택에서 product불러오게 함

---

frontend/src/pages/create-campaign/Page.tsx

Feat: 페이지네이션으로 수정 및 불편한거 수정

---

backend/build.gradle
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/controller/AuthController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/controller/MemberController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/request/LoginRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/request/SignupRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/response/MemberAccountsNo.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/service/MemberService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/controller/PaymentController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/dto/request/PaymentCancellationRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/dto/request/PaymentRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/dto/response/PaymentCancellationResult.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/dto/response/PaymentProcessingResult.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/entity/PaymentEvent.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/repository/PaymentRepository.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/BnplService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/PaymentService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/global/enums/PaymentType.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/global/utils/TransactionSummaryUtil.java
backend/src/test/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/PaymentServiceTest.java

- 결제 참여, 환불
1. 즉시 결제
2. BNPL 결제
3. 즉시 결제 + BNPL 결제
- paymentEvent 속성 변경

Feature: 공동구매 결제 , 환불

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/credit/CreditEvaluationForm.tsx
frontend/src/lib/student-credit-ai.ts
frontend/src/pages/bnpl/Page.tsx
frontend/src/pages/my-page/Page.tsx

Feat: BNPL관련 AI로 판단하는거 일단 AI연동은 해 보았다

---

frontend/src/pages/campaigns/[id]/Page.tsx
frontend/src/pages/create-campaign/Page.tsx
frontend/src/pages/payment/Page.tsx
frontend/src/pages/payment/success/Page.tsx
frontend/src/routes.tsx

Feat: 결제페이지 꾸미고, BNPL분할납부 가능하게

---

frontend/src/components/credit/CreditEvaluationForm.tsx
frontend/src/lib/student-credit-ai.ts

Feat: AI가 어떤식으로 동작하는지 매개변수를 넣었음.

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/client/finopen/dto/request/UpdateDemandDepositAccountTransferRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/controller/PaymentController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/dto/request/PayBNPLRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/entity/PaymentEvent.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/BnplService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/PaymentService.java
backend/src/test/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/BnplServiceTest.java

Feat: pay bnpl

---

frontend/src/pages/bnpl/Page.tsx
frontend/src/pages/my-page/Page.tsx

Feat: 마이페이지랑 BNPL페이지에 연동할 수 있는거 연동

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/controller/MemberDepositController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/request/DepositRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/dto/response/DepositResponse.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/service/DepositService.java

Feature: 회원 계좌에 입금하는 기능

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/controller/MemberController.java

feature: bnpl 한도 업데이트 코멘트 달기

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/member/service/MemberService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/controller/PaymentController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/dto/request/PaymentRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/PaymentService.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/global/exception/GlobalExceptionHandler.java

Fix: refund error

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/BnplService.java

bnpl no session 에러 고침 - Transactional

bnpl no session 에러 고침 - Transactional

---

frontend/src/lib/notification-context.tsx
frontend/src/pages/payment/success/Page.tsx

Feat: 제품 구매시 알람뜸

---

frontend/src/api/Payment.ts
frontend/src/pages/bnpl-repay/Page.tsx
frontend/src/pages/my-page/Page.tsx

Feat: 마이페이지 이거저거고침

---

backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/controller/PaymentController.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/dto/request/PayBNPLRequest.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/entity/PaymentEvent.java
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/BnplService.java

Feature: 부분상환

---

.github/workflows/deploy.yml
backend/src/main/java/xyz/jinjin99/gongguyoung/backend/domain/payment/service/PaymentService.java
frontend/src/pages/bnpl-repay/Page.tsx

Feat: add-env
